#!/bin/env zsh

# File Name: test.sh
# Description: <++>
# Author: zachary
# Created Time: 2020-06-08 00:22:42
# Last Modified: 
local current_dir="${PWD/#$HOME/~}"
if [[ ${current_dir} != '~' ]]; then
    last_dir="${current_dir:t}"
    pre_array=(${(@s:/:)current_dir:h})
    pre=""
    for i in ${pre_array};do
        if [[ ${i:0:1} == '.' ]]; then
            pre+="${i:0:2}/"
        else
            pre+="${i:0:1}/"
        fi
    done
    current_dir="${pre}${last_dir}"
fi

echo $current_dir
